### ISSUE TITLE
hi , i meet some problems when i build solution on VS2012

### ISSUE THREAD

**Issue by btlcmr0702** [bobzhuyb/ns3-rdma#1]
hi
i open the file ns-3-dev.sh by VS2012. But when i build solution i meet this problem and it happened many times:  

> c:\users\ns3-rdma-master\windows\ns-3-dev\headers\ns3\nstime.h(145): error C3861: “lround”: 找不到标识
> ![image](https://cloud.githubusercontent.com/assets/19741892/19728193/09564d00-9bc5-11e6-99e0-e82a9f8a67d5.png)
> May be u can give me some solution , it will be nice ! 
> Thanks

**Comment by btlcmr0702** [comment]
Except the problem above , i also met some other problems, were these problems caused by the version of  g++ or something else? 
23>c:\users\btl\desktop\ns3-rdma-master\src\uan\model\uan-phy-gen.cc(288): error C2059: 语法错误:“数字上的错误后缀”
23>c:\users\btl\desktop\ns3-rdma-master\src\uan\model\uan-phy-gen.cc(288): error C2146: 语法错误: 缺少“}”(在标识符“U”的前面)
23>c:\users\btl\desktop\ns3-rdma-master\src\uan\model\uan-phy-gen.cc(288): error C2146: 语法错误: 缺少“;”(在标识符“U”的前面)
23>c:\users\btl\desktop\ns3-rdma-master\src\uan\model\uan-phy-gen.cc(288): error C2065: “U”: 未声明的标识符
23>c:\users\btl\desktop\ns3-rdma-master\src\uan\model\uan-phy-gen.cc(289): error C2059: 语法错误:“数字上的错误后缀”
23>c:\users\btl\desktop\ns3-rdma-master\src\uan\model\uan-phy-gen.cc(290): error C2146: 语法错误: 缺少“;”(在标识符“U”的前面)
23>c:\users\btl\desktop\ns3-rdma-master\src\uan\model\uan-phy-gen.cc(290): error C2065: “U”: 未声明的标识符
23>c:\users\btl\desktop\ns3-rdma-master\src\uan\model\uan-phy-gen.cc(290): error C2143: 语法错误 : 缺少“;”(在“}”的前面)
23>c:\users\btl\desktop\ns3-rdma-master\src\uan\model\uan-phy-gen.cc(293): error C2065: “sinr”: 未声明的标识符
23>c:\users\btl\desktop\ns3-rdma-master\src\uan\model\uan-phy-gen.cc(297): error C2059: 语法错误:“if”
23>c:\users\btl\desktop\ns3-rdma-master\src\uan\model\uan-phy-gen.cc(298): error C2143: 语法错误 : 缺少“;”(在“{”的前面)
23>c:\users\btl\desktop\ns3-rdma-master\src\uan\model\uan-phy-gen.cc(298): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
23>c:\users\btl\desktop\ns3-rdma-master\src\uan\model\uan-phy-gen.cc(301): error C2059: 语法错误:“if”
23>c:\users\btl\desktop\ns3-rdma-master\src\uan\model\uan-phy-gen.cc(302): error C2143: 语法错误 : 缺少“;”(在“{”的前面)
23>c:\users\btl\desktop\ns3-rdma-master\src\uan\model\uan-phy-gen.cc(302): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
23>c:\users\btl\desktop\ns3-rdma-master\src\uan\model\uan-phy-gen.cc(306): error C2059: 语法错误:“for”
23>c:\users\btl\desktop\ns3-rdma-master\src\uan\model\uan-phy-gen.cc(306): error C2143: 语法错误 : 缺少“)”(在“;”的前面)
23>c:\users\btl\desktop\ns3-rdma-master\src\uan\model\uan-phy-gen.cc(306): error C2143: 语法错误 : 缺少“;”(在“<”的前面)
23>c:\users\btl\desktop\ns3-rdma-master\src\uan\model\uan-phy-gen.cc(306): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
23>c:\users\btl\desktop\ns3-rdma-master\src\uan\model\uan-phy-gen.cc(306): error C2143: 语法错误 : 缺少“;”(在“++”的前面)
23>c:\users\btl\desktop\ns3-rdma-master\src\uan\model\uan-phy-gen.cc(306): error C2086: “int ns3::r”: 重定义
33>c:\users\btl\desktop\ns3-rdma-master\src\wifi\model\nist-error-rate-model.cc(48): error C3861: “erfc”: 找不到标识符

**Comment by btlcmr0702** [comment]
we try to use VS2015 and it seems fine.
so the problems were caused by the version of VS

**Comment by bobzhuyb** [comment]
Yes. It complains about Tools version 14 missing, which means your Visual Studio version is too old. You can get free VS2015 from the link in README. Closing this issue.
