### ISSUE TITLE
Question about some WARNING and ERROR

### ISSUE THREAD

**Issue by wtao0221** [bobzhuyb/ns3-rdma#10]
Hi, Yibo,

I have ported your windows version to linux version based on the ns-3.18. But, I am not quite sure whether I have done things right.

Anyway, the build process terminates successfully.

But there are some ERROR and WARNING messages when I run the default application (third.cc w/ mix/config.txt).

`ERROR: Sendingbuffer miss!`
`WARNING: shouldn't reach here -- socket.h`

So, is the simulation still right? or what happens according to these messages?

**Comment by bobzhuyb** [comment]
Probably not right. Can you find where these outputs are from? It seems that it's not using the right class for socket.

**Comment by wtao0221** [comment]
The error message comes from line 670 src/point-to-point/model/qbb-net-device.cc

The warning message is from line 427 src/network/model/socket.h (in the GetLocalPort() function)
