### ISSUE TITLE
PAUSE never triggered

### ISSUE THREAD

**Issue by xiaoyuan528** [bobzhuyb/ns3-rdma#11]
Hi,
I was doing a simulation using a N:1 (N is big) incast topology, and the buffer is quickly full leading to egress drop, without triggering PAUSE. 
So I went back to check the code, and found out that PAUSE generation is checked (checkqueuefull()) inside the send() function, not the receive() function; also it's checked after the ingress and egress admission check, and the ingress and egress admission are checked at the same time.
I thought first in the receive(), we should check the pause generation and ingressadmission, then in the send(), check egressadmission.
So I am confused here, since the simulation keeps telling me buffer is full without triggering any pause generation.
Thank you.

**Comment by bobzhuyb** [comment]
Ingress and egress admission checks are performed BEFORE the packet enters the buffer. If the dropping thresholds are met, the packet will be immediately dropped. This is the logic of Broadcom Trident family chips. 

How large is your N? Are you using static PFC threshold (check your config.txt)?

In general, the switch model implementation, especially the buffer settings assume 64 ports (align with real Trident chips). If you have more ports, it's possible that you need to tune the parameters in https://github.com/bobzhuyb/ns3-rdma/blob/master/src/network/model/broadcom-node.cc

For example, If you use static PFC threshold and have PFC_threshold * num_of_port > total_buffer_size (9MB, set in https://github.com/bobzhuyb/ns3-rdma/blob/master/src/network/model/broadcom-node.cc), you'll see egress drop before any PFC being triggered. You could try 1. lower the static PFC threshold, 2. enlarge the total buffer (more ports should have more buffer)

**Comment by xiaoyuan528** [comment]
I was using the dynamic threshold, but you are so correct about the port number:)
Thank you.
