### ISSUE TITLE
some questions about the implementation of Timely

### ISSUE THREAD

**Issue by yuntiantian** [bobzhuyb/ns3-rdma#13]
Hi ,
   About timely branch, i study the code but i find i am confused.  
   Where is the algorithm of "timely" implemented?
   In the main function, if i don't use qbb-device, can i simulate the protocol of Timely?
   Thank you for your reply.

**Comment by bobzhuyb** [comment]
Check the commit history

https://github.com/bobzhuyb/ns3-rdma/commit/e8d2d9e594c76f315bf560d2120d9fe9f1bcb459
