### ISSUE TITLE
some questions about the  DCQCN and Timely

### ISSUE THREAD

**Issue by lan1120** [bobzhuyb/ns3-rdma#14]
hello, I have read your paper about analysis of DCQCN and TIMELY. TIMELY has a control engine that inserts delays between segments to achieve the target rate.  And how dose DCQCN achieve the target rate in real NIC or ns3 ? Thank you.

**Comment by bobzhuyb** [comment]
DCQCN rate control is based on per-packet pacing, leveraging the hardware rate limiter in NIC.

NS-3 also implements per-packet pacing.

**Comment by lan1120** [comment]
I understand,Thank you.
