### ISSUE TITLE
Can you tell me what the output is?

### ISSUE THREAD

**Issue by kg12** [bobzhuyb/ns3-rdma#16]
Hello, friend. I ran your code and got the output file mix.tr. But I don't know what the output means. Can you tell me what is the output of each item? Thank you very much.
![image](https://user-images.githubusercontent.com/5936706/40295660-bbf1476c-5d0c-11e8-8446-4eb6f8bd9d4b.png)

**Comment by bobzhuyb** [comment]
Please refer to this:
https://github.com/bobzhuyb/ns3-rdma/issues/3#issuecomment-258340715

**Comment by kg12** [comment]
Thank you for your reply.
