### ISSUE TITLE
I want to run a 100:1 incast, but it always WARNING: Drop because egress Port buffer full!

### ISSUE THREAD

**Issue by lele121314** [bobzhuyb/ns3-rdma#20]
I want to know what parameter I should change?

**Comment by bobzhuyb** [comment]
What is your topology? It may not work if a switch has >64 ports

**Comment by lele121314** [comment]
If I want to support more than 64 ports., what should I do?

**Comment by bobzhuyb** [comment]
https://github.com/bobzhuyb/ns3-rdma/blob/c414c6b91b5959775a77bbb5edc2a95c5a069f9e/src/point-to-point/model/qbb-net-device.h#L45

But you probably also need to tune several detailed parameters in 
https://github.com/bobzhuyb/ns3-rdma/blob/c414c6b91b5959775a77bbb5edc2a95c5a069f9e/src/network/model/broadcom-node.cc#L78-L110

This module is implemented according to the real switch, so I don't recommend to modify it unless you really know what you are doing. If you really want to test port-level incast, which is closely related to switch behavior, you have to understand those parameters anyways. 

If you just care about flow-level incast, you don't need to modify any of these. You can use multi-hop topology or start multiple flows from the same nodes.

**Comment by lele121314** [comment]
ok， thank you very much.

**Comment by lele121314** [comment]
I want to compare the dcqcn with my model. So I need to adjust your configutarions. I need to chenge the m_maxBufferBytes to 80 * 1450, but the result is terrible. I consider maybe the parameters in ns3-rdma/src/network/model/broadcom-node.cc. But I don't know how to tune. Can you give me some suggestions? Thank you vary much.
