### ISSUE TITLE
I want to know how many times the queues drop packets and mark ecn ?

### ISSUE THREAD

**Issue by lele121314** [bobzhuyb/ns3-rdma#21]
I want to know how many times the queues drop packets and mark ecn ? 
I find the network/utils/boadcom-egress-queue.cc::BEgressQueue has the limit of queue and network/model/boadcom-node.cc also has the limit of buffer.
1.So what the difference ? 
2.If I change the queue's MaxBytes in network/utils/boadcom-egress-queue.cc , where should I also change ? 
3.I need to count the drop times and ecn times, where should I add the counter?

**Comment by bobzhuyb** [comment]
BEgressQueue is a generic data structure that can be used by both NICs and switches. Its limit of queue is probably NOT what you are looking for. You should just leave it or set it to be a very large value.

The switch dropping logic is based on the limit of buffer in network/model/boadcom-node.cc
Specifically, here --

https://github.com/bobzhuyb/ns3-rdma/blob/master/src/network/model/broadcom-node.cc#L117-L161

**Comment by lele121314** [comment]
where to mark the ecn flag?
qbb-net-device:
L366:if (egressCongested)
			{
				h.SetEcn((Ipv4Header::EcnType)0x03);
			}

this place?
