### ISSUE TITLE
What does the hops in qbb-net-device mean?

### ISSUE THREAD

**Issue by liyuliang001** [bobzhuyb/ns3-rdma#24]
Hi Yibo,

I am reading the code of qbb-net-device. I see many per-flow variables also have hop indexes (e.g., m_alpha[fCnt][**maxHop**], m_targetRate[fCnt][**maxHop**]). What does the hop mean here? I do not see this concept in the DCQCN paper.

Thanks,
Yuliang

**Comment by bobzhuyb** [comment]
This is for some experimental protocol designs. I believe that I was trying to model the best sending rate of each hop in the network assuming we have per-hop feedback. Later, I set maxHop to 1, so it falls back to the normal DCQCN.

You can ignore it, unless you want to explore something similar.
