### ISSUE TITLE
some questions to kmin translate to m_pg_qcn_threshold.

### ISSUE THREAD

**Issue by DeruiLiu** [bobzhuyb/ns3-rdma#33]
Hi, i have a question about kmin to m_pg_qcn_threshold,. 
![image](https://user-images.githubusercontent.com/32285152/76135571-0af3cc80-6063-11ea-81d2-558920e53b3c.png)
can you tell me why this *1030? and what is the meaning of 1030?

**Comment by bobzhuyb** [comment]
It's RoCE packet MTU. It's usually 1024B ~ 1500B
