### ISSUE TITLE
some questions about pfc pause frame

### ISSUE THREAD

**Issue by lan1120** [bobzhuyb/ns3-rdma#4]
hi,I'm interested in your project.
I want to know how pause frame come to upstream device(NIC).  Pause frame is transmittid based L2.Did you use the Global routing?

**Comment by bobzhuyb** [comment]
No, there is nothing about L3 routing. It's on L2 point-to-point link, which means after one side sends it out, the other side will receive it..

**Comment by lan1120** [comment]
OK, I got it. Thank you!
